[mcp_servers.playwright]
args = [
    "-y",
    "@playwright/mcp@0.0.75",
    "--isolated",
]
command = "npx"

[mcp_servers.sqlite]
args = [
    "-y",
    "mcp-server-sqlite@0.0.2",
    "--db",
    "./gym.db",
]
command = "npx"
