import { StyleSheet } from 'react-native';

import { theme } from '@/theme/Theme';

export const styles = StyleSheet.create({
  content: { gap: theme.spacing.md, padding: theme.spacing.md },
  detail: {
    backgroundColor: theme.colors.bgSecondary,
    borderColor: theme.colors.border,
    borderRadius: theme.radii.lg,
    borderWidth: 1,
    gap: theme.spacing.xs,
    padding: theme.spacing.md,
  },
  detailLabel: {
    color: theme.colors.textAccent,
    fontSize: theme.fonts.size.xs,
    fontWeight: theme.fonts.weight.semibold,
  },
  detailText: {
    color: theme.colors.textSecondary,
    fontSize: theme.fonts.size.sm,
    lineHeight: theme.fonts.lineHeight.sm,
  },
  detailTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.fonts.size.lg,
    fontWeight: theme.fonts.weight.semibold,
  },
  eyebrow: {
    color: theme.colors.textAccent,
    fontSize: theme.fonts.size.xs,
    fontWeight: theme.fonts.weight.semibold,
    lineHeight: theme.fonts.lineHeight.xs,
  },
  flex: { flex: 1 },
  form: { gap: theme.spacing.xs },
  hero: { gap: theme.spacing.sm, paddingTop: theme.spacing.md },
  inlineError: {
    color: theme.colors.textPrimary,
    fontSize: theme.fonts.size.sm,
    lineHeight: theme.fonts.lineHeight.sm,
  },
  input: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radii.md,
    borderWidth: 1,
    color: theme.colors.textPrimary,
    fontSize: theme.fonts.size.md,
    lineHeight: theme.fonts.lineHeight.md,
    minHeight: theme.spacing.xxl * 2,
    padding: theme.spacing.md,
    textAlignVertical: 'top',
  },
  inputFocused: { borderColor: theme.colors.accent, borderWidth: 2 },
  inputLabel: {
    color: theme.colors.textSecondary,
    fontSize: theme.fonts.size.sm,
    fontWeight: theme.fonts.weight.medium,
  },
  primaryButton: {
    ...theme.shadows.control,
    alignItems: 'center',
    backgroundColor: theme.colors.accent,
    borderRadius: theme.radii.md,
    justifyContent: 'center',
    minHeight: theme.spacing.xxl,
    paddingHorizontal: theme.spacing.lg,
  },
  primaryButtonDisabled: { backgroundColor: theme.colors.overlay },
  primaryButtonPressed: {
    backgroundColor: theme.colors.accentPressed,
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  primaryButtonText: {
    color: theme.colors.textInverse,
    fontSize: theme.fonts.size.md,
    fontWeight: theme.fonts.weight.semibold,
    lineHeight: theme.fonts.lineHeight.md,
  },
  saved: {
    color: theme.colors.textAccent,
    fontSize: theme.fonts.size.sm,
    lineHeight: theme.fonts.lineHeight.sm,
  },
  score: {
    color: theme.colors.textPrimary,
    fontSize: theme.fonts.size.display,
    fontWeight: theme.fonts.weight.semibold,
    lineHeight: theme.fonts.lineHeight.display,
  },
  scoreMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.fonts.size.md,
    lineHeight: theme.fonts.lineHeight.md,
  },
  scoreRow: { alignItems: 'flex-end', flexDirection: 'row', gap: theme.spacing.xs },
  screen: { backgroundColor: theme.colors.bgPrimary, flex: 1 },
  segment: {
    alignItems: 'center',
    borderRadius: theme.radii.md,
    flex: 1,
    paddingVertical: theme.spacing.xs,
  },
  segmented: {
    backgroundColor: theme.colors.bgSecondary,
    borderRadius: theme.radii.lg,
    flexDirection: 'row',
    gap: theme.spacing.xxs,
    padding: theme.spacing.xxs,
  },
  segmentPressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
  segmentSelected: { backgroundColor: theme.colors.surfaceRaised },
  segmentText: {
    color: theme.colors.textSecondary,
    fontSize: theme.fonts.size.sm,
    fontWeight: theme.fonts.weight.medium,
  },
  segmentTextSelected: { color: theme.colors.textPrimary },
  stack: { gap: theme.spacing.md },
  summary: {
    color: theme.colors.textSecondary,
    fontSize: theme.fonts.size.md,
    lineHeight: theme.fonts.lineHeight.md,
  },
  title: {
    color: theme.colors.textPrimary,
    fontSize: theme.fonts.size.xxl,
    fontWeight: theme.fonts.weight.semibold,
    lineHeight: theme.fonts.lineHeight.xxl,
  },
  weekButton: {
    borderColor: theme.colors.border,
    borderRadius: theme.radii.md,
    borderWidth: 1,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
  },
  weekButtonSelected: { borderColor: theme.colors.accent },
  weekRow: { flexDirection: 'row', gap: theme.spacing.xs },
  weekText: {
    color: theme.colors.textSecondary,
    fontSize: theme.fonts.size.sm,
    fontWeight: theme.fonts.weight.medium,
  },
});
